# Generated by Django 5.1.1 on 2024-09-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0006_remove_product_image_product_category_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
