# Generated by Django 5.0.6 on 2024-09-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0008_order_customer_name_order_email_order_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
