# Generated by Django 5.0.6 on 2024-09-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0011_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
