# Generated by Django 5.0.6 on 2024-09-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0014_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('In-delivery', 'In-delivery'), ('Delivered', 'Delivered')], default='Received', max_length=20),
        ),
    ]
